#!/usr/bin/env python
# coding: utf-8

# # Supply Chain Analysis

# ## Introduction

# The supply Chain is the network of production and logistics involved in producing and delivering goods to customers.
# Supply Chain Analysis means analyzing various components of a Supply Chain to understand how to improve the effectiveness of the Supply Chain to create more value for customers. 

# ## KPI's Taken Into Consideration

# 1.Relationship between the Price of the products and the Revenue generated by them.<br>
# 2.Sales By Product Type<br>
# 3.Total Revenue By Shipping Carrier<br>
# 4.Average lead time and Average Manufacturing Costs for all products of the company<br>
# 5-Revenue Generated by each SKU<br>
# 6-Stock levels of each SKU<br>
# 7-Order Quantity Of SKU<br>
# 8-Shipping Cost By Carrier<br>
# 9-Cost Distribution By Transportation Mode<br>
# 10-Average Defect Rates by Product Type<br>
# 11-Defect Rates by Transportation Mode<br>

# ## Dataset

# To analyze a company’s supply chain, we need data on the different stages of the supply chain, like data about sourcing, manufacturing, transportation, inventory management, sales and customer demographics.

# I found an ideal dataset for this task which includes data about the supply chain of a Fashion and Beauty startup. You can download the datset from the given link- https://statso.io/supply-chain-analysis-case-study/ .

# ## Importing The Necessary Python Libraries
# 

# In[2]:


import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default="plotly_dark"

data = pd.read_csv(r"C:\Users\Lenovo\OneDrive\Desktop\Datasets\supply_chain.csv")
print(data.head())


# ## Statistical Summary Of Data Frame

# In[3]:


print(data.describe())


# ## Relationship between the Price of the products and the Revenue generated by them

# In[4]:


fig = px.scatter(data, x='Price', 
                 y='Revenue generated', 
                 color='Product type', 
                 hover_data=['Number of products sold'], 
                 trendline="ols")
fig.show()


# The company derives more revenue from skincare products, and the higher the price of skincare products, the more revenue they generate.

# ## Sales By Product Type

# In[6]:


sales_data = data.groupby('Product type')['Number of products sold'].sum().reset_index()

pie_chart = px.pie(sales_data, values='Number of products sold', names='Product type', 
                   title='Sales by Product Type', 
                   hover_data=['Number of products sold'],
                   hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Vivid)
                   
pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()


# 45% of the business comes from skincare products, 29.5% from haircare, and 25.5% from cosmetics.

# ## Total Revenue By Shipping Carrier

# In[7]:


total_revenue = data.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
colors = [ 'orange','white','green']
fig = go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'], 
                     y=total_revenue['Revenue generated']))
fig.update_layout(title='Total Revenue by Shipping Carrier', 
                  xaxis_title='Shipping Carrier', 
                  yaxis_title='Revenue Generated')
fig.update_traces(marker_color='orange')
fig.show()


# So the company is using three carriers for transportation, and Carrier B helps the company in generating more revenue.

#  ## Average lead time and Average Manufacturing Costs for all products of the company

# In[8]:


avg_lead_time = data.groupby('Product type')['Lead time'].mean().reset_index()
avg_manufacturing_costs = data.groupby('Product type')['Manufacturing costs'].mean().reset_index()
result = pd.merge(avg_lead_time, avg_manufacturing_costs, on='Product type')
result.rename(columns={'Lead time': 'Average Lead Time', 'Manufacturing costs': 'Average Manufacturing Costs'}, inplace=True)
print(result)


# ## Analyzing SKUs
# 

# SKU stands for Stock Keeping Units. They’re like special codes that help companies keep track of all the different things they have for sale. Imagine you have a large toy store with lots of toys. Each toy is different and has its name and price, but when you want to know how many you have left, you need a way to identify them. So you give each toy a unique code, like a secret number only the store knows. This secret number is called SKU.

# ### Revenue Generated by each SKU

# In[9]:


revenue_chart = px.line(data, x='SKU', y='Revenue generated', title='Revenue Generated by SKU',
                        color_discrete_sequence=['violet'])

revenue_chart.show()


# ### Stock levels of each SKU

# In[11]:


stock_chart = px.line(data, x='SKU', 
                      y='Stock levels', 
                      title='Stock Levels by SKU',color_discrete_sequence=['green'])

stock_chart.show()


# ### Order Quantity Of SKU

# In[12]:


order_quantity_chart = px.bar(data, x='SKU', 
                              y='Order quantities', 
                              title='Order Quantity by SKU')
order_quantity_chart.update_traces(marker_color='yellow')
order_quantity_chart.show()


# ## Cost Analysis

# ### Shipping Cost By Carrier

# In[13]:


shipping_cost_chart = px.bar(data, x='Shipping carriers', 
                             y='Shipping costs', 
                             title='Shipping Costs by Carrier')
shipping_cost_chart.update_traces(marker_color='red')
shipping_cost_chart.show()


# In one of the above visualizations, we discovered that Carrier B helps the company in more revenue. It is also the most costly Carrier among the three.

# ### Cost Distribution By Transportation Mode

# In[14]:


transportation_chart = px.pie(data, 
                              values='Costs', 
                              names='Transportation modes', 
                              title='Cost Distribution by Transportation Mode',
                              hole=0.5,
                              color_discrete_sequence=px.colors.qualitative.Pastel2)
transportation_chart.show()


# So the company spends more on Road and Rail modes of transportation for the transportation of Goods.

# ## Defect Rate Analysis

# ### Average Defect Rates by Product Type

# In[15]:


defect_rates_by_product = data.groupby('Product type')['Defect rates'].mean().reset_index()

fig = px.bar(defect_rates_by_product, x='Product type', y='Defect rates',
             title='Average Defect Rates by Product Type')
fig.show()


# So the defect rate of haircare products is higher.

# ### Defect Rates by Transportation Mode

# In[16]:


pivot_table = pd.pivot_table(data, values='Defect rates', 
                             index=['Transportation modes'], 
                             aggfunc='mean')

transportation_chart = px.pie(values=pivot_table["Defect rates"], 
                              names=pivot_table.index, 
                              title='Defect Rates by Transportation Mode',
                              hole=0.5,
                              color_discrete_sequence=px.colors.qualitative.Pastel)
transportation_chart.show()


# Road transportation results in a higher defect rate, and Air transportation has the lowest defect rate.
